name: Update Profile SVG

on:
  schedule:
    # Runs every 8 hours
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  update_svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch GitHub Stats
        id: fetch_stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        run: |
          USER_API_DATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/$USERNAME")
          NUM_REPOS=$(echo "$USER_API_DATA" | jq -r '.public_repos')

          REPOS_API_DATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/users/$USERNAME/repos?per_page=100&sort=pushed")
          NUM_STARS=$(echo "$REPOS_API_DATA" | jq -r '[.[] | .stargazers_count] | add')

          COMMIT_COUNT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/search/commits?q=author:$USERNAME" | jq -r '.total_count')
          PR_COUNT=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/search/issues?q=is:pr+author:$USERNAME" | jq -r '.total_count')

          LANG_API_DATA=$(curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=$USERNAME&format=json&langs_count=5")
          LANG_LIST=$(echo "$LANG_API_DATA" | jq -r 'keys_unsorted | @sh' | tr -d "'") # Format as a clean, comma-separated list
          
          SVG_TEXT_BLOCK="<tspan x='10' dy='0'>Number of repos:      ${NUM_REPOS}         Number of stars: ${NUM_STARS}</tspan>"
          SVG_TEXT_BLOCK="${SVG_TEXT_BLOCK}<tspan x='10' dy='1.2em'>Number of commits: ${COMMIT_COUNT}         Number of PR's:   ${PR_COUNT}</tspan>"
          SVG_TEXT_BLOCK="${SVG_TEXT_BLOCK}<tspan x='10' dy='1.2em'>Most used languages: ${LANG_LIST}</tspan>"

          echo "STATS_BLOCK<<EOF" >> $GITHUB_OUTPUT
          echo "$SVG_TEXT_BLOCK" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update SVG template
        run: |
          sed "s#{github_stats}#${{ steps.fetch_stats.outputs.STATS_BLOCK }}#g" ./res/arch_profile_template.svg > ./res/arch_profile_current.svg

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(docs): update profile stats SVG"
          file_pattern: ./res/arch_profile_current.svg
