name: Update Profile SVG

on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

jobs:
  update_svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Fetch GitHub Stats
        id: fetch_stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
        run: |
          validate_json() {
            if ! echo "$1" | jq -e . > /dev/null; then
              echo "::error::API call failed or did not return valid JSON. The workflow cannot continue."
              echo "Response was: $1"
              exit 1
            fi
          }
          GH_REPO_DATA=$(gh repo list --owner "$USERNAME" --limit 1000 --json isFork,stargazersCount)
          validate_json "$GH_REPO_DATA"
          NUM_REPOS=$(echo "$GH_REPO_DATA" | jq '[.[] | select(.isFork | not)] | length')
          NUM_STARS=$(echo "$GH_REPO_DATA" | jq '[.[].stargazersCount] | add')
          COMMIT_DATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.cloak-preview" "https://api.github.com/search/commits?q=author:$USERNAME")
          validate_json "$COMMIT_DATA"
          COMMIT_COUNT=$(echo "$COMMIT_DATA" | jq '.total_count')
          PR_DATA=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/search/issues?q=is:pr+author:$USERNAME")
          validate_json "$PR_DATA"
          PR_COUNT=$(echo "$PR_DATA" | jq '.total_count')
          LANG_API_DATA=$(curl -s "https://github-readme-stats.vercel.app/api/top-langs/?username=$USERNAME&format=json&langs_count=5&hide_border=true&layout=compact")
          if ! echo "$LANG_API_DATA" | jq -e . > /dev/null; then
            LANG_LIST="Data not available"
          else
            LANG_LIST=$(echo "$LANG_API_DATA" | jq -r 'keys_unsorted | join(", ")')
            if [ -z "$LANG_LIST" ]; then
              LANG_LIST="Not enough data yet"
            fi
          fi
          SVG_TEXT_BLOCK="<tspan x='10' dy='0'>Number of repos:      ${NUM_REPOS}         Number of stars: ${NUM_STARS}</tspan>"
          SVG_TEXT_BLOCK="${SVG_TEXT_BLOCK}<tspan x='10' dy='1.2em'>Number of commits: ${COMMIT_COUNT}         Number of PR's:   ${PR_COUNT}</tspan>"
          SVG_TEXT_BLOCK="${SVG_TEXT_BLOCK}<tspan x='10' dy='1.2em'>Most used languages: ${LANG_LIST}</tspan>"
          echo "STATS_BLOCK<<EOF" >> $GITHUB_OUTPUT
          echo "$SVG_TEXT_BLOCK" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Update SVG template
        run: |
          sed "s#{github_stats}#${{ steps.fetch_stats.outputs.STATS_BLOCK }}#g" ./res/arch_profile_template.svg > ./res/arch_profile_current.svg

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(docs): update profile stats SVG"
          file_pattern: ./res/arch_profile_current.svg
